version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 222634367630.dkr.ecr.ap-south-1.amazonaws.com
      - echo Configuring kubectl...
      - aws eks update-kubeconfig --region ap-south-1 --name third-cluster 
      - echo Checking Kubernetes nodes...
      - kubectl get nodes || echo "Failed to get nodes, continuing..."

  build:
    commands:
      - echo Building Docker image...
      - docker build -t practice-app .
      - echo Tagging Docker image...
      - docker tag practice-app:latest 222634367630.dkr.ecr.ap-south-1.amazonaws.com/practice-app:latest

  post_build:
    commands:
      - echo Pushing Docker images to Amazon ECR...
      - docker push 222634367630.dkr.ecr.ap-south-1.amazonaws.com/practice-app:latest
      - echo Verifying Kubernetes connectivity...
      - kubectl cluster-info || echo "Failed to get cluster info, continuing..."
      - kubectl get pods --namespace=default || echo "Failed to get pods, continuing..."
      - echo Updating Kubernetes deployment...
      - kubectl set image deployment/practice-app practice-app=222634367630.dkr.ecr.ap-south-1.amazonaws.com/practice-app:latest --namespace=default
      - kubectl rollout restart  deployment practice-app --namespace=default
